//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Departures
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Departures()
        {
            this.Passengers = new HashSet<Passengers>();
        }
    
        public int CodeDeparture { get; set; }
        public int Flight { get; set; }
        public System.DateTime DepartureTime { get; set; }
        public int Plane { get; set; }
        public string CrewCommander { get; set; }
    
        public virtual Flights Flights { get; set; }
        public virtual Planes Planes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Passengers> Passengers { get; set; }
    }
}
