//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flights
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Flights()
        {
            this.Departures = new HashSet<Departures>();
        }
    
        public int FlightCode { get; set; }
        public int FlightNumber { get; set; }
        public string DepartureAirport { get; set; }
        public int DestAirport { get; set; }
        public int FlightDuration { get; set; }
        public decimal TicketPrice { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Departures> Departures { get; set; }
        public virtual DestinationAirports DestinationAirports { get; set; }
    }
}
