//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Passengers
    {
        public int CodePassenger { get; set; }
        public int Departure { get; set; }
        public int SeatNumber { get; set; }
        public string FIO { get; set; }
        public string Passport { get; set; }
    
        public virtual Departures Departures { get; set; }
    }
}
